/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package math_solution;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Naeem ur Rahman
 */
public class Combination extends javax.swing.JFrame {
private int n;
private int r;
    /**
     * Creates new form Combination
     */
    public Combination() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSetTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtSetChoose = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Combination");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Find the Combination");

        jLabel2.setText("Enter Total set Objects (n)");

        jLabel3.setText("Enter set choosed Objects (r)");

        txtSetTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSetTotalKeyPressed(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Run");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtSetChoose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSetChooseKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSetTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSetChoose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(53, 53, 53)
                        .addComponent(jButton2)
                        .addGap(24, 24, 24))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSetTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSetChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(53, 53, 53))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                if(validity()){
                    n = Integer.parseInt(txtSetTotal.getText().trim());
                    r = Integer.parseInt(txtSetChoose.getText().trim());
                     long as=solve();
                    if (as<0){
                        JOptionPane.showMessageDialog(Combination.this, "Invalid Answer & Out of Range",null,JOptionPane.ERROR_MESSAGE);
                        return;
                    }
            JOptionPane.showMessageDialog(Combination.this, "Answer is "+as);
            resetField();
            txtSetTotal.grabFocus();
            return;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtSetTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSetTotalKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
              if(validity()){
                    n = Integer.parseInt(txtSetTotal.getText().trim());
                    r = Integer.parseInt(txtSetChoose.getText().trim());
                     long as=solve();
                    if (as<0){
                        JOptionPane.showMessageDialog(Combination.this, "Invalid Answer & Out of Range",null,JOptionPane.ERROR_MESSAGE);
                        return;
                    }
            JOptionPane.showMessageDialog(Combination.this, "Answer is "+as);
            resetField();
            txtSetTotal.grabFocus();
            return;
        }
        }
        
    }//GEN-LAST:event_txtSetTotalKeyPressed

    private void txtSetChooseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSetChooseKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
              if(validity()){
                    n = Integer.parseInt(txtSetTotal.getText().trim());
                    r = Integer.parseInt(txtSetChoose.getText().trim());
                    long as=solve();
                    if (as<0){
                        JOptionPane.showMessageDialog(Combination.this, "Invalid Answer & Out of Range",null,JOptionPane.ERROR_MESSAGE);
                        return;
                    }
            JOptionPane.showMessageDialog(Combination.this, "Answer is "+as);
            resetField();
            txtSetTotal.grabFocus();
            return;
        }
        }
    }//GEN-LAST:event_txtSetChooseKeyPressed
 
    protected long solve(){
       int up=1,n,dw=1,r;
        
        n=this.n;
        r=this.r;
       
        int  r1=1;
        int cr=r;
	r=n-r;
	for (int a=1;a<=n;a++){
		
		up=up*a;
	}
	for (int a=1;a<=r;a++){
		
		dw=dw*a;
	}
	for (int a=1;a<=cr;a++)
	{
		r1=r1*a;
	}

       // return (up/dw);
       return up/(r1*dw);        
    }
    protected boolean validity(){
    if (txtSetTotal.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(Combination.this, "Enter  Value !",null , JOptionPane.ERROR_MESSAGE);
        txtSetTotal.grabFocus();
        return false;
    }
    if (txtSetChoose.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(Combination.this, "Enter  Value !",null , JOptionPane.ERROR_MESSAGE);
        txtSetChoose.grabFocus();
        return false;
    }
    return true;
    
}
    protected void resetField(){
        txtSetTotal.setText("");
        txtSetChoose.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Combination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Combination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Combination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Combination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Combination().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtSetChoose;
    private javax.swing.JTextField txtSetTotal;
    // End of variables declaration//GEN-END:variables
}
