/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package math_solution;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;


/**
 *
 * @author Naeem ur Rahman
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        btnExit.grabFocus();
        showDate();
        showTime();
    }
///////////////////////////////////////////////////date&Time///////////////////////////////
       void showDate() {

        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        DateLab.setText(s.format(d));
    }

    void showTime() {
   new Timer(0, new ActionListener() {

       @Override
       public void actionPerformed(ActionEvent ae) {
          Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("hh-mm-ss a");
        TimeLab.setText(s.format(d));
       }
   }).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        MainHeading = new javax.swing.JLabel();
        btnCalculator = new javax.swing.JButton();
        btnFactorial = new javax.swing.JButton();
        btnPermutation = new javax.swing.JButton();
        btnCombination = new javax.swing.JButton();
        btnQuadratic = new javax.swing.JButton();
        TimeLab = new javax.swing.JLabel();
        DateLab = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        Background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        mItemNew = new javax.swing.JMenuItem();
        mItemExit = new javax.swing.JMenuItem();
        menuRun = new javax.swing.JMenu();
        mItemFactorial = new javax.swing.JMenuItem();
        mItemPermutation = new javax.swing.JMenuItem();
        mItemCombination = new javax.swing.JMenuItem();
        mItemQuadratic = new javax.swing.JMenuItem();
        mItemCalculator = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        mItemAbout = new javax.swing.JMenuItem();

        jButton7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton7.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Math Soution");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainHeading.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        MainHeading.setForeground(new java.awt.Color(255, 255, 255));
        MainHeading.setText("Math Solution Application");
        getContentPane().add(MainHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        btnCalculator.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btnCalculator.setText("Calculator");
        btnCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculatorActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 174, 76));

        btnFactorial.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btnFactorial.setText("Factorial");
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });
        getContentPane().add(btnFactorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 174, 76));

        btnPermutation.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnPermutation.setText("Permutation");
        btnPermutation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermutationActionPerformed(evt);
            }
        });
        getContentPane().add(btnPermutation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 174, 76));

        btnCombination.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnCombination.setText("Combination");
        btnCombination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombinationActionPerformed(evt);
            }
        });
        getContentPane().add(btnCombination, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 174, 80));

        btnQuadratic.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnQuadratic.setText("Quadratic Equation");
        btnQuadratic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuadraticActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuadratic, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 174, 76));

        TimeLab.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TimeLab.setForeground(new java.awt.Color(204, 204, 204));
        TimeLab.setText("Time");
        getContentPane().add(TimeLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 574, 190, 40));

        DateLab.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DateLab.setForeground(new java.awt.Color(204, 204, 204));
        DateLab.setText("Date");
        getContentPane().add(DateLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 574, 190, 40));

        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/math_solution/background1.png"))); // NOI18N
        Background.setText("jLabel1");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 650));

        menuFile.setText("File");

        mItemNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mItemNew.setText("New");
        mItemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemNewActionPerformed(evt);
            }
        });
        menuFile.add(mItemNew);

        mItemExit.setText("Exit");
        mItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemExitActionPerformed(evt);
            }
        });
        menuFile.add(mItemExit);

        jMenuBar1.add(menuFile);

        menuRun.setText("Programs");

        mItemFactorial.setText("Factorial");
        mItemFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemFactorialActionPerformed(evt);
            }
        });
        menuRun.add(mItemFactorial);

        mItemPermutation.setText("nPr");
        mItemPermutation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemPermutationActionPerformed(evt);
            }
        });
        menuRun.add(mItemPermutation);

        mItemCombination.setText("nCr");
        mItemCombination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCombinationActionPerformed(evt);
            }
        });
        menuRun.add(mItemCombination);

        mItemQuadratic.setText("Quadratic Equation");
        menuRun.add(mItemQuadratic);

        mItemCalculator.setText("Calculator");
        mItemCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCalculatorActionPerformed(evt);
            }
        });
        menuRun.add(mItemCalculator);

        jMenuBar1.add(menuRun);

        menuHelp.setText("Help");

        mItemAbout.setText("About");
        mItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAboutActionPerformed(evt);
            }
        });
        menuHelp.add(mItemAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mItemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemNewActionPerformed
        // TODO add your handling code here:
        new MainWindow().setVisible(true);
    }//GEN-LAST:event_mItemNewActionPerformed

    private void mItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mItemExitActionPerformed

    private void mItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(MainWindow.this, "This is Application is made for the Solution for the Math Problems");
    }//GEN-LAST:event_mItemAboutActionPerformed

    private void mItemFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemFactorialActionPerformed
        // TODO add your handling code here:
        new Factorial().setVisible(true);
    }//GEN-LAST:event_mItemFactorialActionPerformed

    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
        // TODO add your handling code here:
         new Factorial().setVisible(true);
    }//GEN-LAST:event_btnFactorialActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPermutationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermutationActionPerformed
        // TODO add your handling code here:
       new Permutation().setVisible(true);
    }//GEN-LAST:event_btnPermutationActionPerformed

    private void btnCombinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombinationActionPerformed
        // TODO add your handling code here:
        new Combination().setVisible(true);
    }//GEN-LAST:event_btnCombinationActionPerformed

    private void mItemPermutationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemPermutationActionPerformed
        // TODO add your handling code here:
         new Permutation().setVisible(true);
    }//GEN-LAST:event_mItemPermutationActionPerformed

    private void mItemCombinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCombinationActionPerformed
        // TODO add your handling code here:
        new Combination().setVisible(true);
    }//GEN-LAST:event_mItemCombinationActionPerformed

    private void btnCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculatorActionPerformed
       new Calculator().setVisible(true);
    }//GEN-LAST:event_btnCalculatorActionPerformed

    private void mItemCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCalculatorActionPerformed
        new Calculator().setVisible(true);
    }//GEN-LAST:event_mItemCalculatorActionPerformed

    private void btnQuadraticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuadraticActionPerformed
       new QuadraticEquation().setVisible(true);
    }//GEN-LAST:event_btnQuadraticActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel DateLab;
    private javax.swing.JLabel MainHeading;
    private javax.swing.JLabel TimeLab;
    private javax.swing.JButton btnCalculator;
    private javax.swing.JButton btnCombination;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnPermutation;
    private javax.swing.JButton btnQuadratic;
    private javax.swing.JButton jButton7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mItemAbout;
    private javax.swing.JMenuItem mItemCalculator;
    private javax.swing.JMenuItem mItemCombination;
    private javax.swing.JMenuItem mItemExit;
    private javax.swing.JMenuItem mItemFactorial;
    private javax.swing.JMenuItem mItemNew;
    private javax.swing.JMenuItem mItemPermutation;
    private javax.swing.JMenuItem mItemQuadratic;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuRun;
    // End of variables declaration//GEN-END:variables
}
