/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package math_solution;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Naeem ur Rahman
 */
public class Permutation extends javax.swing.JFrame {
private int n;
private int r;
    /**
     * Creates new form Permutation
     */
    public Permutation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTotalObject = new javax.swing.JTextField();
        txtSelectedObject = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnRun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Permutation");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Find the Permutation");

        jLabel2.setText("Enter Total Object (n)");

        jLabel3.setText("Enter Slected Objects (r) ");

        txtTotalObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalObjectActionPerformed(evt);
            }
        });
        txtTotalObject.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTotalObjectKeyPressed(evt);
            }
        });

        txtSelectedObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSelectedObjectActionPerformed(evt);
            }
        });
        txtSelectedObject.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSelectedObjectKeyPressed(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnRun.setText("Run");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });
        btnRun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnRunKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(45, 45, 45)
                        .addComponent(btnRun))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtSelectedObject, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addComponent(txtTotalObject)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotalObject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtSelectedObject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRun)
                    .addComponent(jButton1))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTotalObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalObjectActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_txtTotalObjectActionPerformed

    private void txtSelectedObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelectedObjectActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSelectedObjectActionPerformed

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        // TODO add your handling code here:
        if(validity()){
                    n = Integer.parseInt(txtTotalObject.getText().trim());
                    r = Integer.parseInt(txtSelectedObject.getText().trim());
            JOptionPane.showMessageDialog(Permutation.this, "Answer is "+solve());
            resetField();
            txtTotalObject.grabFocus();
            return;
        }
    }//GEN-LAST:event_btnRunActionPerformed

    private void btnRunKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRunKeyPressed
        // TODO add your handling code here:

        
        
    }//GEN-LAST:event_btnRunKeyPressed

    private void txtTotalObjectKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalObjectKeyPressed
        // TODO add your handling code here:
               if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            if(validity()){
            n = Integer.parseInt(txtTotalObject.getText().trim());
            r = Integer.parseInt(txtSelectedObject.getText().trim());
            JOptionPane.showMessageDialog(Permutation.this, "Answer is "+solve());
            resetField();
            txtTotalObject.grabFocus();
            return;
        }
        }
    }//GEN-LAST:event_txtTotalObjectKeyPressed

    private void txtSelectedObjectKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSelectedObjectKeyPressed
        // TODO add your handling code here:
               if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            if(validity()){
            n = Integer.parseInt(txtTotalObject.getText().trim());
            r = Integer.parseInt(txtSelectedObject.getText().trim());
            JOptionPane.showMessageDialog(Permutation.this, "Answer is "+solve());
            resetField();
            txtTotalObject.grabFocus();
            return;
        }
        }
    }//GEN-LAST:event_txtSelectedObjectKeyPressed
    protected long solve(){
       int up=1,n,dw=1,r;
        
        n=this.n;
        r=this.r;
       
        // int  r1=1;
        //int cr=r;
	r=n-r;
	for (int a=1;a<=n;a++){
		
		up=up*a;
	}
	for (int a=1;a<=r;a++){
		
		dw=dw*a;
	}
	/*for (int a=1;a<=cr;a++)
	{
		r1=r1*a;
	}*/

        return (up/dw);
       //return up/(r1*dw);        
    }
    protected boolean validity(){
    if (txtTotalObject.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(Permutation.this, "Enter Value !",null , JOptionPane.ERROR_MESSAGE);
        txtTotalObject.grabFocus();
        return false;
    }
    if (txtSelectedObject.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(Permutation.this, "Enter Value !",null , JOptionPane.ERROR_MESSAGE);
        txtSelectedObject.grabFocus();
        return false;
    }
    return true;
    
}
    protected void resetField(){
        txtTotalObject.setText("");
        txtSelectedObject.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Permutation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Permutation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Permutation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Permutation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Permutation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRun;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtSelectedObject;
    private javax.swing.JTextField txtTotalObject;
    // End of variables declaration//GEN-END:variables
}
